### ISSUE TITLE
Inverse the flag?

### ISSUE THREAD

**Issue by IanaKhitsko** [Finderstein/MIPZ_Practice1#10]
https://github.com/Finderstein/MIPZ_Practice1/blob/7e818aa3c8111ac5eee78b833ec5759c33abaaa3/calculator.js#L151

you use only < !countryNotComplete>. Why can;t we have  countryNotComplete function then?

**Comment by Finderstein** [comment]
You mean to separate this check into another function? Or to rewrite the checker before and in result we will have flag that shows that country IS complete?

**Comment by IanaKhitsko** [comment]
Sorry, my issue was incorrectly formulated. I meant <countryComplete> function. We inverse the result anyway

**Comment by Finderstein** [comment]
You know, we will do both of those. We will separate this check into another function AND rewrite it so it shows that country is complete for better readability.

**Comment by Finderstein** [comment]
Fixed in commit [cba404e](https://github.com/Finderstein/MIPZ_Practice1/commit/cba404ea0856e937dffe4cba3426493e161b0a37#diff-074b96f16fd84e394409f422b1eeb42a61fea6263645e08c8888e79990785d95R144)
