### ISSUE TITLE
Remove unnecessary `start()` function

### ISSUE THREAD

**Issue by Veetaha** [Finderstein/MIPZ_Practice1#2]
The `start()` function here is unnecessary. It adds nothing but just more code:
https://github.com/Finderstein/MIPZ_Practice1/blob/f751d0168e5d5f015bc81c8c4a5e5628030f8bea/app.js#L4-L22

We can remove it and put all code at top-level.

**Comment by Finderstein** [comment]
It is legacy code from the project development start. Considering that the other logic is distributed between other files now, we can safely delete it. Thanks for your remark. Will fix in next MR.
