### ISSUE TITLE
Reduce variable shadowing

### ISSUE THREAD

**Issue by Veetaha** [Finderstein/MIPZ_Practice1#3]
The variable `row` is shadowed within the loop body here:
https://github.com/Finderstein/MIPZ_Practice1/blob/f751d0168e5d5f015bc81c8c4a5e5628030f8bea/calculator.js#L34-L35

To reduce confusion and improve code readability, you'd better rename one of the variables.

**Comment by Finderstein** [comment]
Yeah, you are right. Will fix it next iteration. It is probably a typo.
