### ISSUE TITLE
The application crashes on invalid user input

### ISSUE THREAD

**Issue by Veetaha** [Finderstein/MIPZ_Practice1#4]
The input isn't validated here:
https://github.com/Finderstein/MIPZ_Practice1/blob/f751d0168e5d5f015bc81c8c4a5e5628030f8bea/interface.js#L16-L26

If the user doesn't provide enough information, the program crashes with array index out of bounds error.

**Comment by Finderstein** [comment]
Huge mistake from our side. Will fix it in next version. Thank you for your input, it pretty important for us
