### ISSUE TITLE
Strange var name

### ISSUE THREAD

**Issue by IanaKhitsko** [Finderstein/MIPZ_Practice1#5]
https://github.com/Finderstein/MIPZ_Practice1/blob/7e818aa3c8111ac5eee78b833ec5759c33abaaa3/calculator.js#L34

why columnCount and rowCount? why count for index/interator?

**Comment by Finderstein** [comment]
We chose this var name for better understanding of what we are doing as we work with matrix

**Comment by IanaKhitsko** [comment]
Ok, but 'count' usually mean the number of container elements. I don't insist, but it would be better to change to iteration var to '*index' or smth like this. But again, just to let you know, I don't insist.

**Comment by Finderstein** [comment]
Hmm yeah, you are right. I thought that you mean to rename it to 'index' or something like that, not 'rowIndex' and 'rowIndex'. I misunderstood you. We will change that in near time.

**Comment by Finderstein** [comment]
Fixed this here [cba404e](https://github.com/Finderstein/MIPZ_Practice1/commit/cba404ea0856e937dffe4cba3426493e161b0a37#diff-074b96f16fd84e394409f422b1eeb42a61fea6263645e08c8888e79990785d95R38)
