### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by IanaKhitsko** [Finderstein/MIPZ_Practice1#6]
https://github.com/Finderstein/MIPZ_Practice1/blob/7e818aa3c8111ac5eee78b833ec5759c33abaaa3/calculator.js#L66

Please don't use magic numbers in the code, introduce consts

**Comment by Finderstein** [comment]
You're right. We will fix this

**Comment by Finderstein** [comment]
Fixed it. You can review changes here [cba404e](https://github.com/Finderstein/MIPZ_Practice1/commit/cba404ea0856e937dffe4cba3426493e161b0a37#diff-074b96f16fd84e394409f422b1eeb42a61fea6263645e08c8888e79990785d95R70)
