### ISSUE TITLE
Can country be null here?

### ISSUE THREAD

**Issue by IanaKhitsko** [Finderstein/MIPZ_Practice1#7]
https://github.com/Finderstein/MIPZ_Practice1/blob/7e818aa3c8111ac5eee78b833ec5759c33abaaa3/calculator.js#L113

Can country be null here?

**Comment by Finderstein** [comment]
Yes it can. For example if we have input France 1 1 2 2 we will initialize array like this:
[[0, 0, 0],
 [0, 1, 1],
 [0, 1, 1]]
where 0 represents empty object. If we take transactionCity from this '0' it will be empty object so it will not have country parameter.
