### ISSUE TITLE
Magic consts again

### ISSUE THREAD

**Issue by IanaKhitsko** [Finderstein/MIPZ_Practice1#8]
https://github.com/Finderstein/MIPZ_Practice1/blob/7e818aa3c8111ac5eee78b833ec5759c33abaaa3/calculator.js#L117

please introduce const for 1000

**Comment by Finderstein** [comment]
Will do. Thanks for your pointer

**Comment by Finderstein** [comment]
Fixed it here [cba404e](https://github.com/Finderstein/MIPZ_Practice1/commit/cba404ea0856e937dffe4cba3426493e161b0a37#diff-074b96f16fd84e394409f422b1eeb42a61fea6263645e08c8888e79990785d95R121)
